[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.32.0"
ci = "github"
recursive-tarball = false
packages = ["trnovel"]
precise-builds = true
installers = ["shell", "powershell", "npm", "homebrew"]
targets = ["aarch64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
npm-scope = "@trnovel"
tag-namespace = "trnovel"
publish-jobs = ["./publish-npm", "homebrew"]
github-custom-job-permissions = { "publish-npm" = { contents = "read", id-token = "write" } }
tap = "yexiyue/homebrew-tap"
install-path = "CARGO_HOME"
install-updater = false
msvc-crt-static = false
pr-run-mode = "plan"

[dist.dependencies.apt]
libssl-dev = '*'
pkg-config = '*'
