cmake_minimum_required(VERSION 3.24)
project(zipvoice_phonemizer LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL")
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(USE_ASYNC OFF CACHE BOOL "" FORCE)
set(USE_MBROLA OFF CACHE BOOL "" FORCE)
set(USE_LIBSONIC OFF CACHE BOOL "" FORCE)
set(USE_LIBPCAUDIO OFF CACHE BOOL "" FORCE)
add_subdirectory(espeak espeak-build)
add_executable(zipvoice-phonemizer main.cpp)
target_link_libraries(zipvoice-phonemizer PRIVATE espeak-ng espeak-include)
target_include_directories(zipvoice-phonemizer PRIVATE espeak/src/ucd-tools/src/include)
if(MSVC)
  target_compile_options(zipvoice-phonemizer PRIVATE /utf-8)
endif()
