[package]
name = "novel-tts"
version = "0.1.0"
edition = "2024"
description = "Terminal reader for novel"
authors = ["yexiyue <yexiyue666@qq.com>"]
license = "MIT"
keywords = ["Novel", "TTS"]
repository = "https://github.com/yexiyue/parse-book-source"

[dependencies]
anyhow.workspace = true
dirs = "6.0.0"
futures.workspace = true
kokoro-tts = "0.3.1"
# kokoro-tts = { path = "/Users/yexiyue/rust-project/kokoro" }
reqwest = { version = "0.12.24", default-features = false, features = [
    "json",
    "rustls-tls",
    "cookies",
] }
rodio = { version = "0.21.1", default-features = false, features = [
    "playback",
    "wav",
    "crossbeam-channel",
] }
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
