name: CI # Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libssl-dev pkg-config cmake ninja-build
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --locked --features trnovel/tts,parse-book-source/browser,parse-book-source/js-host,parse-book-source/schema,novel-tts/qwen,novel-tts/voxcpm,novel-tts/omnivoice,novel-tts/coreml,novel-tts/ort-cuda,qwen3-tts/profiling --workspace --lib --tests --examples

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libssl-dev pkg-config cmake ninja-build
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libssl-dev pkg-config cmake ninja-build
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Clippy check
        run: cargo clippy --all-targets --features trnovel/tts,parse-book-source/browser,parse-book-source/js-host,parse-book-source/schema,novel-tts/qwen,novel-tts/voxcpm,novel-tts/omnivoice,novel-tts/coreml,novel-tts/ort-cuda,qwen3-tts/profiling --workspace -- -D warnings

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libssl-dev pkg-config cmake ninja-build
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items --features trnovel/tts,parse-book-source/browser,parse-book-source/js-host,parse-book-source/schema,novel-tts/qwen,novel-tts/voxcpm,novel-tts/omnivoice,novel-tts/coreml,novel-tts/ort-cuda,qwen3-tts/profiling --workspace --examples
